// Translated from https://github.com/peterkagey/apps-peterkagey-com/blob/main/app/helpers/card_trick_helper.rb by ChatGPT.
function cardsToShow(cards) {
  const numberOfCards = cards.length;
  const remainder = cards.reduce((a, b) => a + b, 0) % numberOfCards;
  const sortedCards = [...cards].sort((a, b) => a - b);
  return [
    ...sortedCards.slice(0, remainder),
    ...sortedCards.slice(remainder + 1, numberOfCards)
  ];
}

function possibleValues(shownCards) {
  const n = shownCards.length + 1;
  const remainder = shownCards.reduce((a, b) => a + b, 0) % n;
  const ranges = [0, ...[...shownCards].sort((a, b) => a - b), a030495(shownCards.length) + 1];

  let possible = [];
  for (let i = 0; i < ranges.length - 1; i++) {
    const a = ranges[i];
    const b = ranges[i + 1];
    for (let x = a + 1; x < b; x++) {
      if ((x + remainder) % n === i) {
        possible.push(x);
      }
    }
  }
  return possible;
}

function assistantOrder(cards) {
  const shown = cardsToShow(cards);
  const missing = cards.find(c => !shown.includes(c));
  const communicable = possibleValues(shown);
  const cardIndex = communicable.indexOf(missing);

  const indices = [...Array(shown.length).keys()];
  const perms = permutations(indices);

  const perm = perms[cardIndex];
  return perm.map(i => shown[i]);
}

function magicianGuess(shownCards) {
  const possibilities = possibleValues(shownCards);
  const sorted = [...shownCards].sort((a, b) => a - b);
  const perms = permutations(sorted);

  const index = perms.findIndex(
    perm => perm.every((v, i) => v === shownCards[i])
  );

  return possibilities[index];
}

function a030495(n) {
  let fact = 1;
  for (let i = 2; i <= n + 1; i++) fact *= i;
  return fact + n;
}

function permutations(arr) {
  if (arr.length <= 1) return [arr];
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const current = arr[i];
    const remaining = arr.slice(0, i).concat(arr.slice(i + 1));
    const subPerms = permutations(remaining);
    for (const p of subPerms) {
      result.push([current, ...p]);
    }
  }
  return result;
}

// Generated by ChatGPT
document.getElementById("assistant-button").addEventListener("click", () => {
  const input = document.getElementById("assistant-input").value;
  const values = input
    .split(",")
    .map(s => parseInt(s.trim(), 10))
    .filter(n => !isNaN(n));

  const order = assistantOrder(values);
  document.getElementById("assistant-answer").textContent = order.join(", ");
});

document.getElementById("magician-button").addEventListener("click", () => {
  const input = document.getElementById("magician-input").value;
  const values = input
    .split(",")
    .map(s => parseInt(s.trim(), 10))
    .filter(n => !isNaN(n));

  const guess = magicianGuess(values);
  document.getElementById("magician-answer").textContent = guess;
});
